#!/usr/bin/perl

$|=1;

#
# configuration tool for linoratix
#

#
# Perl Modules
use strict;
use Data::Dumper;

#
# Linoratix Module
use Linoratix;

#
# global variables
our $linoratix = Linoratix->new();
our $VERSION   = "0.0.1";
our $plugin;

sub show_version
{
	$linoratix->message("linoratix-conf version: $VERSION\n");
}

sub load_plugin
{
	my $_plugin = $linoratix->param("plugin");
	eval("use Linoratix::$_plugin;");
	if($@) {
		$linoratix->error("Plugin \"$_plugin\" not found.\n");
		return 0;
	}
	eval("\$plugin = Linoratix::$_plugin->new()");
	if($@) {
		$linoratix->error("Error loading plugin \"$_plugin\".\n");
		$linoratix->error("$@\n\n");
		return 0;
	}
}

sub main
{
	show_version() if($linoratix->option("version"));
	load_plugin()  if($linoratix->param("plugin"))
}


main();

